### ISSUE TITLE
You are using Orange, but you have not set upstream servers for your project.

### ISSUE THREAD

**Issue by cbcye** [syhily/docker-orange#1]
how to configure the upstream?

**Comment by zhengxiaochuan-3** [comment]
这个是提示你根据自己的需求，去配置 nginx upstream 。
涉及到业务逻辑的东西肯定不会写在默认配置文件的。
@cbcye

**Comment by syhily** [comment]
en, it's easy to add your own upstream servers after creating a orange container by using
`docker exec -it xxxx /bin/bash`
`vi /usr/local/orange/nginx.conf`

This may not awesome, but I don't know any better way. PR is welcome.

**Comment by syhily** [comment]
or we could using `include` directive in `nginx.conf` file, the outer configuration file may be easy to add to a exist orange container like: `docker run -v $OUT_CONF_DIR/:/usr/local/orange/upstream_conf`
