### ISSUE TITLE
Dockerfile Build failed 

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [syhily/docker-orange#2]
Step 17 : RUN nginx -V     && lord version
 ---> Running in e5a78b7bbcba
nginx version: openresty/1.11.2.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
built with OpenSSL 1.0.2j  26 Sep 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.60 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.06 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.6 --add-module=../ngx_lua_upstream-0.06 --add-module=../headers-more-nginx-module-0.31 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.17 --add-module=../redis2-nginx-module-0.13 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.07 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-openssl=/tmp/openssl-1.0.2j --with-pcre=/tmp/pcre-8.39 --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-ipv6 --with-mail --with-mail_ssl_module --with-md5-asm --with-pcre-jit --with-sha1-asm --with-stream --with-stream_ssl_module --with-threads
**/usr/bin/env: resty: No such file or directory**
The command '/bin/sh -c nginx -V     && lord version' returned a non-zero code: 127

**Comment by zhengxiaochuan-3** [comment]
好像是因为最新的 openresty 已经不再提供 resty 这个命令行工具了？

**Comment by zhengxiaochuan-3** [comment]
@syhily

**Comment by syhily** [comment]
Would be resolved after the stable release of orange 0.6

**Comment by zhengxiaochuan-3** [comment]
ok , when orange 0.6 will be release ?

**Comment by syhily** [comment]
I would start a nightly build on 0.6 branch this weekend.

**Comment by syhily** [comment]
Fixed on latest commit.
