### ISSUE TITLE
使用docker-compose时，lua无法解析mysql-host

### ISSUE THREAD

**Issue by liyf-kiloseed** [syhily/docker-orange#4]
compose.yml内容如下：

    version: '2'
    services:
    db:
        image: mysql
        expose:
          - "3306"
        environment:
          - MYSQL_ROOT_PASSWORD=docker
        privileged: true

    gateway:
        image: syhily/docker-orange
        ports:
          - "27777:7777"
          - "28888:8888"
          - "29999:9999"
        security_opt:
          - seccomp:unconfined
        environment:
          - ORANGE_DATABASE=orange
          - ORANGE_HOST=orange-database
          - ORANGE_PORT=3306
          - ORANGE_USER=root
          - ORANGE_PWD=docker
        depends_on:
          - db
        links:
          - db:orange-database
        privileged: true

启动后，ping orange-database可以访问，但使用控制台操作数据库相关，报错[error] 26#26: *7 [lua] mysql_db.lua:30: query(): failed to connect: failed to connect: orange-database could not be resolved (3: Host not found): nil nil, client: 172.22.0.1, server: , request: "POST /redirect/enable HTTP/1.1", host: "127.0.0.1:29999", referrer: "http://127.0.0.1:29999/redirect"

这要怎么处理呢？使用docker run的命令是OK的。

**Comment by syhily** [comment]
嗯，这是一个问题，和我使用的 NS Resolver 有关。Orange Docker 版内部使用 dnsmasq 做Nginx 的 resolver，所以就会出现此问题，稍后我会打个补丁就好了。

**Comment by liyf-kiloseed** [comment]
嗯，回复真快，赞。

**Comment by zorrofox** [comment]
如果非docker默认网络，可以直接在resolv.dnsmasq.conf加上一条docker内部的dns 127.0.0.11，但是如果直接改DockerFile好像不太优雅。

------------------------------------------------------------------------------
改了一下，看能不能审核merge一下。谢谢！
