### ISSUE TITLE
Is there too many layers of creating docker?

### ISSUE THREAD

**Issue by Raxxor** [syhily/docker-orange#6]
Why not combained these commands into 1 or 2 ?
Even "nginx -V" RUN indepently...
If we combained and reduce neccessary cmds, it will reduce layers, and left more layers to users

# 1) Add User
# 2) Add configuration file & bootstrap file
# 3) Fix file permission

RUN \
    useradd www \
    && echo "www:www" | chpasswd \
    && echo "www   ALL=(ALL)       ALL" >> /etc/sudoers

RUN \
    mkdir -p ${ORANGE_PATH}/logs \
    && chown -R www:www ${ORANGE_PATH}/*

# Show installization info for debug

RUN \
    nginx -V

# Set the default command to execute
# when creating a new container

ADD docker-entrypoint.sh docker-entrypoint.sh
RUN \
    chmod 755 docker-entrypoint.sh
COPY docker-entrypoint.sh /usr/local/bin

**Comment by syhily** [comment]
Sorry for my poor docker knowledge. I would reduce my dockerfile build commands ASAP.

**Comment by syhily** [comment]
@Raxxor 

```
16.8 MB	RUN |2 LOR_VERSION=0.3.0 ORANGE_VERSION=0.6.3 /bin/sh -c yum install...
1.2 MB	RUN |2 LOR_VERSION=0.3.0 ORANGE_VERSION=0.6.3 /bin/sh -c cd /tmp ...
2.3 kB	RUN |2 LOR_VERSION=0.3.0 ORANGE_VERSION=0.6.3 /bin/sh -c useradd www...
1.1 MB	RUN |2 LOR_VERSION=0.3.0 ORANGE_VERSION=0.6.3 /bin/sh -c mkdir -p ${...
RUN |2 LOR_VERSION=0.3.0 ORANGE_VERSION=0.6.3 /bin/sh -c nginx -V
685 bytes	ADD file:b827533aebd0a7411788632a82ffaf02b8b77b208af07f4503edbda2529...
RUN |2 LOR_VERSION=0.3.0 ORANGE_VERSION=0.6.3 /bin/sh -c chmod 755 d...
751 bytes	COPY file:b827533aebd0a7411788632a82ffaf02b8b77b208af07f4503edbda252...
EXPOSE 7777/tcp 8888/tcp 9999/tcp
32 bytes	ENTRYPOINT ["docker-entrypoint.sh"]
```
The layers created by orange dockerfile is so small, The main question for this issue should be the drop of openresty images.

**Comment by syhily** [comment]
Fixed in https://github.com/syhily/docker-orange/commit/76c4512a7becd5e31e21ee3d5a7c0508fb4202e6

**Comment by syhily** [comment]
```
67.2 MB	ADD file:807143da05d70138e54c4a25c6c3ea64ad1096982333ef3b94a366580be40f52 in /
LABEL name=CentOS Base Image vendor=CentOS license=GPLv2 build-date=20170406
CMD ["/bin/bash"]
MAINTAINER Syhily, syhily@[hidden]
ENV ORANGE_PATH=/usr/local/orange
ARG LOR_VERSION=0.3.0
ARG ORANGE_VERSION=0.6.3
693 bytes	ADD file:b827533aebd0a7411788632a82ffaf02b8b77b208af07f4503edbda25295ac10 in docker-entrypoint.sh
32.4 MB	RUN |2 LOR_VERSION=0.3.0 ORANGE_VERSION=0.6.3 /bin/sh -c chmod 755 d...
EXPOSE 7777/tcp 8888/tcp 9999/tcp
32 bytes	ENTRYPOINT ["docker-entrypoint.sh"]
```

The new layer analysis report. Tks for your issue. This method reduced the image size a bit.

**Comment by Raxxor** [comment]
it's better :+1:

**Comment by noname007** [comment]
good work
