### ISSUE TITLE
orange docker 最新版运行插件错误

### ISSUE THREAD

**Issue by li-keli** [syhily/docker-orange#7]
刚从https://store.docker.com/community/images/syhily/orange 下载的最新镜像。

按照提供的文档，数据库和应用运行正常。
但是在开始插件的时候，提示**failed to enable plugin**
![icon](http://oss.likeli.xin/Blog/2017%E5%B9%B46%E6%9C%8819%E6%97%A5/2.png)

在控制台上看到的，除了第一个 start 全局统计插件是启动的，其他所有的插件都不能够启动。
![icon](http://oss.likeli.xin/Blog/2017%E5%B9%B46%E6%9C%8819%E6%97%A5/1.png)

运行` docker exec -it orange orange version `的版本是`0.6.4`
@syhily @sumory

**Comment by syhily** [comment]
能否去 docker 裡面看一下日誌的報錯是什麼呢？

**Comment by li-keli** [comment]
我使用`docker logs -f orange`来查看日志：

```shell
sed: -e expression #1, char 40: unterminated `s' command
```

**Comment by syhily** [comment]
可以 exec -it bash 進 docker 容器，日誌在 `/usr/local/orange/logs` 下。

**Comment by li-keli** [comment]
好的，谢谢帮助，这是 error.log 的截图:
![icon](http://likeli-public.oss-cn-shanghai.aliyuncs.com/Blog/2017%E5%B9%B46%E6%9C%8819%E6%97%A5/error.png)

这是 dashboard_error.log 的截图：
![icon](http://likeli-public.oss-cn-shanghai.aliyuncs.com/Blog/2017%E5%B9%B46%E6%9C%8819%E6%97%A5/dashboard_error.png)

**Comment by sumory** [comment]
感觉像是没初始化数据

**Comment by li-keli** [comment]
我执行了这份SQL文件：https://github.com/sumory/orange/blob/master/install/orange-v0.6.4.sql

表都已经创建了，除了meta表之外，每张表里面都有一条记录。

meta表是空的。请问是这里有问题吗？

**Comment by sumory** [comment]
![image](https://user-images.githubusercontent.com/1326893/27276600-4aee6f7e-550e-11e7-88df-a5cf1edd0dcc.png)
这个错误说MySQL好像连不上啊

**Comment by syhily** [comment]
目測是創建容器的時候的啟動命令錯了，不需要包含外側的大括號。

**Comment by li-keli** [comment]
我使用的命令是：
```shell
docker run -d --name orange \
    --link orange-database:orange-database \
    -P \
    --security-opt seccomp:unconfined \
    -e ORANGE_DATABASE={orange} \
    -e ORANGE_HOST=orange-database \
    -e ORANGE_PORT={3306} \
    -e ORANGE_USER={orange} \
    -e ORANGE_PWD={pwd} \
    syhily/orange
```

MySql也咋同一台机器上的Docker容器里面，我远程通过上面的这个账号，是可以连接上去的。

**Comment by li-keli** [comment]
汗颜，是的，我忘了这个细节了。

麻烦各位了，多谢帮助。
